version: "3.8"
services:
  mysqldb:
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=stations
    security_opt:
      - seccomp:unconfined
    volumes:
      - mysql:/var/lib/mysql
      - mysql_config:/etc/mysql

  app:
    build: app
    container_name: crawler
    restart: always
    ports:
      - 5000:5000
    volumes:
      - "./app/src:/src"

volumes:
  mysql:
  mysql_config:
